/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
* 1,2,3,5,8,13,21,34,55,89,…
*


*/

fn main() {
    println!("{}", fibonachi_even(4_000_000));
}

fn fibonachi_even(treshold: usize) -> usize {
    let mut sum: usize = 0;
    let mut last: usize = 1;
    let mut current: usize = 1;

    while current < treshold - 1 {
        if current % 2 == 0 {
            sum += current;
        }

        let swap = current + last;
        last = current;
        current = swap;
    }
    sum
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fibonach_even() {
        assert_eq!(fibonachi_even(100), 44);
    }
}
